### ISSUE TITLE
Introducing any new Entity file into Entity folder creating error: Cycle\Annotated\Exception\AnnotationException: 

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/demo#325]
### What do you get instead? The below error.

Yiisoft\ErrorHandler\Exception\ErrorException: Trying to access array offset on value of type null in C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php:1369
Stack trace:
#0 C:\wamp64\www\yii-invoice\vendor\yiisoft\error-handler\src\ErrorHandler.php(122): Yiisoft\ErrorHandler\Exception\ErrorException->__construct(message: ''Trying to acce...', code: '2', severity: '2', filename: ''C:\\\\wamp64\\\\ww...', line: '1369', previous: '???')
#1 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(1369): Yiisoft\ErrorHandler\ErrorHandler::Yiisoft\ErrorHandler\{closure:C:\wamp64\www\yii-invoice\vendor\yiisoft\error-handler\src\ErrorHandler.php:116-123}(severity: '2', message: ''Trying to acce...', file: ''C:\\\\wamp64\\\\ww...', line: '1369')
#2 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(1336): Doctrine\Common\Annotations\DocParser->ArrayEntry()
#3 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(1237): Doctrine\Common\Annotations\DocParser->Arrayx()
#4 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(1300): Doctrine\Common\Annotations\DocParser->PlainValue()
#5 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(1220): Doctrine\Common\Annotations\DocParser->FieldAssignment()
#6 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(1053): Doctrine\Common\Annotations\DocParser->Value()
#7 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(1035): Doctrine\Common\Annotations\DocParser->Values()
#8 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(869): Doctrine\Common\Annotations\DocParser->MethodCall()
#9 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(719): Doctrine\Common\Annotations\DocParser->Annotation()
#10 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(376): Doctrine\Common\Annotations\DocParser->Annotations()
#11 C:\wamp64\www\yii-invoice\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationReader.php(146): Doctrine\Common\Annotations\DocParser->parse(input: ''/**\\r\\n * @Ent...', context: ''class App\\\\Inv...')
#12 C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Internal\DoctrineAnnotationReader.php(48): Doctrine\Common\Annotations\AnnotationReader->getClassAnnotations(class: 'class Reflectio...')
#13 C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Internal\DoctrineAnnotationReader.php(109): Spiral\Attributes\Internal\DoctrineAnnotationReader->Spiral\Attributes\Internal\{closure:C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Internal\DoctrineAnnotationReader.php:47-49}()
#14 C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Internal\DoctrineAnnotationReader.php(49): Spiral\Attributes\Internal\DoctrineAnnotationReader->wrapDoctrineExceptions(then: 'class Closure {...')
#15 C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Internal\Decorator.php(41): Spiral\Attributes\Internal\DoctrineAnnotationReader->getClassMetadata(class: 'class Reflectio...', name: ''Cycle\\\\Annotat...')
#16 C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Composite\Composite.php(38): Spiral\Attributes\AnnotationReader->getClassMetadata(class: 'class Reflectio...', name: ''Cycle\\\\Annotat...')
#17 C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Composite\SelectiveReader.php(22): Spiral\Attributes\Composite\Composite::Spiral\Attributes\Composite\{closure:C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Composite\Composite.php:37-39}(reader: 'class Spiral\\At...')
#18 C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Composite\Composite.php(39): Spiral\Attributes\Composite\SelectiveReader->each(resolver: 'class Closure {...')
#19 C:\wamp64\www\yii-invoice\vendor\spiral\attributes\src\Reader.php(21): Spiral\Attributes\Composite\SelectiveReader->getClassMetadata(class: 'class Reflectio...', name: ''Cycle\\\\Annotat...')
#20 C:\wamp64\www\yii-invoice\vendor\cycle\annotated\src\Embeddings.php(51): Spiral\Attributes\Composite\SelectiveReader->firstClassMetadata(class: 'class Reflectio...', name: ''Cycle\\\\Annotat...')
#21 C:\wamp64\www\yii-invoice\vendor\cycle\schema-builder\src\Compiler.php(65): Cycle\Annotated\Embeddings->run(registry: 'class Cycle\\Sch...')
#22 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Schema\Provider\FromConveyorSchemaProvider.php(42): Cycle\Schema\Compiler->compile(registry: 'class Cycle\\Sch...', generators: '[0 => class Cyc...', defaults: '???')
#23 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Schema\Provider\Support\DeferredSchemaProviderDecorator.php(52): Yiisoft\Yii\Cycle\Schema\Provider\FromConveyorSchemaProvider->read(nextProvider: 'NULL')
#24 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Schema\Provider\Support\SchemaProviderPipeline.php(24): Yiisoft\Yii\Cycle\Schema\Provider\Support\DeferredSchemaProviderDecorator->read(latestProvider: 'NULL')
#25 C:\wamp64\www\yii-invoice\config\packages\yiisoft\yii-cycle\common.php(55): Yiisoft\Yii\Cycle\Schema\Provider\Support\SchemaProviderPipeline->read(nextProvider: '???')
#26 C:\wamp64\www\yii-invoice\vendor\yiisoft\injector\src\Injector.php(66): Yiisoft\Config\Config::{closure:C:\wamp64\www\yii-invoice\config\packages\yiisoft\yii-cycle\common.php:54-60}(container: 'class Yiisoft\\Y...')
#27 C:\wamp64\www\yii-invoice\vendor\yiisoft\injector\src\Injector.php(66): ReflectionFunction->invokeArgs(args: '[0 => class Yii...')
#28 C:\wamp64\www\yii-invoice\vendor\yiisoft\factory\src\Definition\CallableDefinition.php(37): Yiisoft\Injector\Injector->invoke(callable: 'class Closure {...', arguments: '???')
#29 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(370): Yiisoft\Factory\Definition\CallableDefinition->resolve(container: 'class Yiisoft\\D...')
#30 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(318): Yiisoft\Di\Container->buildInternal(id: ''Cycle\\\\ORM\\\\Sc...')
#31 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(144): Yiisoft\Di\Container->build(id: ''Cycle\\\\ORM\\\\Sc...')
#32 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-debug\src\Proxy\ContainerInterfaceProxy.php(78): Yiisoft\Di\Container->get(id: ''Cycle\\\\ORM\\\\Sc...')
#33 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-debug\src\Proxy\ContainerInterfaceProxy.php(58): Yiisoft\Yii\Debug\Proxy\ContainerProxy->getInstance(id: ''Cycle\\\\ORM\\\\Sc...')
#34 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Factory\OrmFactory.php(31): Yiisoft\Yii\Debug\Proxy\ContainerProxy->get(id: ''Cycle\\\\ORM\\\\Sc...')
#35 C:\wamp64\www\yii-invoice\vendor\yiisoft\injector\src\Injector.php(66): Yiisoft\Yii\Cycle\Factory\OrmFactory->__invoke(container: 'class Yiisoft\\Y...')
#36 C:\wamp64\www\yii-invoice\vendor\yiisoft\injector\src\Injector.php(66): ReflectionFunction->invokeArgs(args: '[0 => class Yii...')
#37 C:\wamp64\www\yii-invoice\vendor\yiisoft\factory\src\Definition\CallableDefinition.php(37): Yiisoft\Injector\Injector->invoke(callable: 'class Yiisoft\\Y...', arguments: '???')
#38 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(370): Yiisoft\Factory\Definition\CallableDefinition->resolve(container: 'class Yiisoft\\D...')
#39 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(318): Yiisoft\Di\Container->buildInternal(id: ''Cycle\\\\ORM\\\\OR...')
#40 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(144): Yiisoft\Di\Container->build(id: ''Cycle\\\\ORM\\\\OR...')
#41 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Factory\RepositoryProvider.php(25): Yiisoft\Di\Container->get(id: ''Cycle\\\\ORM\\\\OR...')
#42 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(420): Yiisoft\Yii\Cycle\Factory\RepositoryProvider->register(container: 'class Yiisoft\\D...')
#43 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(395): Yiisoft\Di\Container->addProvider(providerDefinition: ''Yiisoft\\\\Yii\\\\...')
#44 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(88): Yiisoft\Di\Container->addProviders(providers: '['yiisoft/widge...')
#45 C:\wamp64\www\yii-invoice\src\ApplicationRunner.php(56): Yiisoft\Di\Container->__construct(definitions: '['Yiisoft\\Rbac\\...', providers: '['yiisoft/widge...', tags: '[]', rootContainer: 'NULL', validate: 'TRUE')
#46 C:\wamp64\www\yii-invoice\public\index.php(24): App\ApplicationRunner->run()
#47 {main}

Next Cycle\Annotated\Exception\AnnotationException: Trying to access array offset on value of type null in C:\wamp64\www\yii-invoice\vendor\cycle\annotated\src\Embeddings.php:53
Stack trace:
#0 C:\wamp64\www\yii-invoice\vendor\cycle\schema-builder\src\Compiler.php(65): Cycle\Annotated\Embeddings->run(Object(Cycle\Schema\Registry))
#1 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Schema\Provider\FromConveyorSchemaProvider.php(42): Cycle\Schema\Compiler->compile(Object(Cycle\Schema\Registry), Array)
#2 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Schema\Provider\Support\DeferredSchemaProviderDecorator.php(52): Yiisoft\Yii\Cycle\Schema\Provider\FromConveyorSchemaProvider->read(NULL)
#3 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Schema\Provider\Support\SchemaProviderPipeline.php(24): Yiisoft\Yii\Cycle\Schema\Provider\Support\DeferredSchemaProviderDecorator->read(NULL)
#4 C:\wamp64\www\yii-invoice\config\packages\yiisoft\yii-cycle\common.php(55): Yiisoft\Yii\Cycle\Schema\Provider\Support\SchemaProviderPipeline->read()
#5 [internal function]: Yiisoft\Config\Config::{closure}(Object(Yiisoft\Yii\Debug\Proxy\ContainerProxy))
#6 C:\wamp64\www\yii-invoice\vendor\yiisoft\injector\src\Injector.php(66): ReflectionFunction->invokeArgs(Array)
#7 C:\wamp64\www\yii-invoice\vendor\yiisoft\factory\src\Definition\CallableDefinition.php(37): Yiisoft\Injector\Injector->invoke(Object(Closure))
#8 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(370): Yiisoft\Factory\Definition\CallableDefinition->resolve(Object(Yiisoft\Di\CompositeContainer))
#9 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(318): Yiisoft\Di\Container->buildInternal('Cycle\\ORM\\Schem...')
#10 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(144): Yiisoft\Di\Container->build('Cycle\\ORM\\Schem...')
#11 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-debug\src\Proxy\ContainerInterfaceProxy.php(78): Yiisoft\Di\Container->get('Cycle\\ORM\\Schem...')
#12 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-debug\src\Proxy\ContainerInterfaceProxy.php(58): Yiisoft\Yii\Debug\Proxy\ContainerInterfaceProxy->getInstance('Cycle\\ORM\\Schem...')
#13 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Factory\OrmFactory.php(31): Yiisoft\Yii\Debug\Proxy\ContainerInterfaceProxy->get('Cycle\\ORM\\Schem...')
#14 [internal function]: Yiisoft\Yii\Cycle\Factory\OrmFactory->__invoke(Object(Yiisoft\Yii\Debug\Proxy\ContainerProxy))
#15 C:\wamp64\www\yii-invoice\vendor\yiisoft\injector\src\Injector.php(66): ReflectionFunction->invokeArgs(Array)
#16 C:\wamp64\www\yii-invoice\vendor\yiisoft\factory\src\Definition\CallableDefinition.php(37): Yiisoft\Injector\Injector->invoke(Object(Closure))
#17 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(370): Yiisoft\Factory\Definition\CallableDefinition->resolve(Object(Yiisoft\Di\Container))
#18 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(318): Yiisoft\Di\Container->buildInternal('Cycle\\ORM\\ORMIn...')
#19 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(144): Yiisoft\Di\Container->build('Cycle\\ORM\\ORMIn...')
#20 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Factory\RepositoryProvider.php(25): Yiisoft\Di\Container->get('Cycle\\ORM\\ORMIn...')
#21 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(420): Yiisoft\Yii\Cycle\Factory\RepositoryProvider->register(Object(Yiisoft\Di\Container))
#22 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(395): Yiisoft\Di\Container->addProvider('Yiisoft\\Yii\\Cyc...')
#23 C:\wamp64\www\yii-invoice\vendor\yiisoft\di\src\Container.php(88): Yiisoft\Di\Container->addProviders(Array)
#24 C:\wamp64\www\yii-invoice\src\ApplicationRunner.php(56): Yiisoft\Di\Container->__construct(Array, Array, Array, NULL, true)
#25 C:\wamp64\www\yii-invoice\public\index.php(24): App\ApplicationRunner->run()
#26 {main}

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.0.2
| Operating system | Windows 10 Wampserver 3.2.5, Apache 2.4.46, mySql 5.7.31

Inserting a new entity.php file into the Entity folder has created the above error which is normally symptomatic with a change in php version. I have upgraded composer.php php requirements. I see yiisoft/cycle is compatible with "php": "^7.4|^8.0",  Fork: rossaddison/yii-invoice.

**Comment by rossaddison** [comment]
I thought initially that this was a php problem but it appears that it is putting too many entity files into the entity folder at once. I removed all the new entities and any temporary subfolder out of the main Entity folder and gradually reintroduced them one by one. Cycle is now identifying errors on each file.
