### ISSUE TITLE
Config broken

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/demo#338]
REF https://github.com/yiisoft/config/pull/73

ON DEMO APP NOW 

```php
ErrorException: Duplicate key "yiisoft/yii-console" in configs:
 - config/packages/yiisoft/yii-console/params.php
 - config/packages/yiisoft/yii-cycle/params.php
 - config/packages/yiisoft/yii-debug/params.php in /var/www/html/site/vendor/yiisoft/config/src/Config.php:379
Stack trace:
#0 /var/www/html/site/vendor/yiisoft/config/src/Config.php(250): Yiisoft\Config\Config->throwException('Duplicate key "...')
#1 /var/www/html/site/vendor/yiisoft/config/src/Config.php(148): Yiisoft\Config\Config->merge(Array, '', Array, Array, Array)
#2 /var/www/html/site/vendor/yiisoft/config/src/Config.php(79): Yiisoft\Config\Config->buildGroup('params', '/')
#3 /var/www/html/site/src/ApplicationRunner.php(52): Yiisoft\Config\Config->get('web')
#4 /var/www/html/site/public/index.php(24): App\ApplicationRunner->run()
#5 {main}
```

**Comment by samdark** [comment]
Here's the latest build: https://github.com/yiisoft/demo/runs/3403204742 It passes.
